include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 120 # Maximum line width before wrapping
  trailing_commas: preserve # Preserve trailing commas in multi-line collections

linter:
  rules:
    require_trailing_commas: true # Ensure trailing commas in collections for readability
    prefer_single_quotes: true # Prefer single quotes for strings
    avoid_print: true # Avoid leaving debug print statements in production

    constant_identifier_names: false # Allow non-UPPER_CASE constants
    non_constant_identifier_names: false # Allow non-lowerCamelCase variable names

    prefer_const_constructors: true # Use const constructors whenever possible
    prefer_const_literals_to_create_immutables: true # Prefer const for list/map/set literals
    prefer_const_declarations: true # Prefer const for variables when possible
    prefer_const_constructors_in_immutables: true # Prefer const in immutable classes

    avoid_unnecessary_containers: true # Avoid Container widgets when not needed
    prefer_final_fields: true # Prefer final for class fields when possible

    unnecessary_null_checks: true # Warn about unnecessary null checks
    unnecessary_lambdas: false # Avoid redundant lambda expressions

analyzer:
  errors:
    unnecessary_const: error
    unnecessary_type_check: error
    unused_element: error
    unnecessary_non_null_assertion: error
